### ISSUE TITLE
terraform container resource naming error

### ISSUE THREAD

**Issue by knoxknot** [Qovery/terraform-provider-qovery#143]
The naming for the container resource conflicts with the naming for the container registry resource.
![naming_error](https://user-images.githubusercontent.com/23431146/206510684-ffea406e-5ca9-4d59-bdb4-f14e8010e9f5.png)

**Comment by evoxmusic** [comment]
Hi @knoxknot , thank you for reporting this issue

**Comment by knoxknot** [comment]
Perfect. Thanks, @benjaminch.
