### ISSUE TITLE
Environment variables set to the empty string "" error out

### ISSUE THREAD

**Issue by spacedub** [Qovery/terraform-provider-qovery#152]
```
resource "qovery_container" "some-container" {

  environment_variables = [
    {
      key = "FOO"
      value = ""
    },
  ]
}
```

Will result in:

```
╷
│ Error: Error on container create line 417
│
│   with qovery_container.registry-cache-container,
│   on qovery.tf line 109, in resource "qovery_container" "registry-cache-container":
│  109: resource "qovery_container" "registry-cache-container" {
│
│ failed to create container: invalid container upsert request: invalid variable diff request: invalid
│ variable upsert request: Key: 'UpsertRequest.Value' Error:Field validation for 'Value' failed on the
│ 'required' tag
```

(as the `Value: ""` seem to be dropped from the struct before / during  validation, resulting in the validator complaining as it is marked `required`).

Note: this is useful when a container sets an env variable by default (eg: in the Dockerfile), and you want to change that to "".

**Comment by spacedub** [comment]
Seems to be a problem with qovery overall, and not just the terraform provider, right,?

Looking at Qovery console:

<img width="539" alt="Screenshot 2023-01-17 at 11 23 56 AM" src="https://user-images.githubusercontent.com/104954251/212993486-f0f48765-3417-45f7-a601-0e5adc9785dd.png">

**Comment by spacedub** [comment]
For whoever ends-up here, there is a workaround.
Just abuse variable interpolation with a non-existent variable to get the empty string...

eg:
`TLS={{CHEAT}}`

Will give you the desired result...

**Comment by mzottolaqovery** [comment]
Hello @spacedub,
We don't allow empty string for environment variable value.
For the moment it works with the interpolation trick, but it may stop working the day we'll validate the interpolation (not defined in the roadmap yet)

Can you describe more your case ? What prevents you to set the variable value to a non-empty value ?

**Comment by spacedub** [comment]
Hey @mzottolaqovery 

Thanks for your answer.

> We don't allow empty string for environment variable value.
> What prevents you to set the variable value to a non-empty value ?

Because in that case I really need this variable to be ""... the underlying software will use that variable value to decide whether to enable certain features if the variable is set to a non-empty string, or disable them otherwise, and by default it is enabled.

Think about it another way: if an env variable has been set in a Dockerfile to a certain default value (non-empty string), how do I set it to "" at runtime?

 The empty string is just as legit a value as any other for an env variable...

Hope that helps.

**Comment by mzottolaqovery** [comment]
Thanks for your use-case description.
I've added this need to our backlog, we will prioritize it soon.

**Comment by mzottolaqovery** [comment]
Hello @spacedub 
You can now specify an empty value for a variable with our terraform provider.
This will be available soon also on our console
