### ISSUE TITLE
Wrong documentation for `resource container`

### ISSUE THREAD

**Issue by sebastienblanc** [Qovery/terraform-provider-qovery#157]
In https://registry.terraform.io/providers/Qovery/qovery/latest/docs/resources/container , I think the intro paragraph is wrong "Use this data source to retrieve information about an existing container." , it's not a `data source` but a `resource`

**Comment by mzottolaqovery** [comment]
Hello @sebastienblanc, Indeed the auto generation of the documentation is incoherent on this one. 
I'm looking

**Comment by mzottolaqovery** [comment]
Fixed in last version
