### ISSUE TITLE
Use built-in environment variables into app 

### ISSUE THREAD

**Issue by evoxmusic** [Qovery/terraform-provider-qovery#16]
Hi @benamib 👋🏽 ,

When using the Terraform provider with a database and an application. It's impossible to bind the application to the database without knowing the *built-in* environment variables and secrets injected at the Environment level. It would be great to have a way to predetermine those environment variables inject them into the application. 

Here is a design suggestion:

```
resource "qovery_database" "psql" {
  //...
}

resource "qovery_application" "backend" {
  // ...
  environment_variables = [
    {
      key = "HOST"
      value = qovery_database.psql.internal_host
    }
  ] 
}
```

Note: the built-in environment variables can be known only after the database creation.

cc @alecarrano @florianlepont

**Comment by evoxmusic** [comment]
Hey @benamib 👋🏽 any idea when you'll be able to handle this one? 🙏🏽

**Comment by json-lbtn** [comment]
👍
