### ISSUE TITLE
Upgrade to terraform-plugin-framework > 1.x

### ISSUE THREAD

**Issue by dirien** [Qovery/terraform-provider-qovery#244]
Hi,

are there any plans in the near future to upgrade this provider to the newer versions of the `github.com/hashicorp/terraform-plugin-framework`?

**Comment by benjaminch** [comment]
Hi @dirien 

It's planned on our end, but no ETA yet. It introduces a major breaking change on our end and requires an heavy refactoring.

Out of curiosity, why do you want this version?

Cheers !

**Comment by dirien** [comment]
It would help me to create a Pulumi provider for it!

**Comment by mzottola** [comment]
Hello @dirien 
The terraform provider has been upgraded to use the `1.4.2` of terraform plugin framework
