### ISSUE TITLE
Add AWS vpc peering in qovery_cluster ressource

### ISSUE THREAD

**Issue by deromemont** [Qovery/terraform-provider-qovery#38]
Let the possibility to use vpc peering in qovery_cluster creation
The idea is to terraform this ressource with the vpc peering creation in AWS for hybrid environment

**Comment by benamib** [comment]
Hi @deromemont 
Thanks you for this suggestion. This feature was not planned for the next version but as it shouldn't that long to implement, i'll try to push this with the next release.
fyi: v0.3.0 is planned for early next week

**Comment by evoxmusic** [comment]
Thank you @deromemont for your feedback :)
