### ISSUE TITLE
Add "domain" attribute to terraform resource "qovery_helm"

### ISSUE THREAD

**Issue by whitedr** [Qovery/terraform-provider-qovery#386]
Similar to this issue: #74

https://registry.terraform.io/providers/Qovery/qovery/latest/docs/resources/helm

This terraform resource is missing "domain" attribute - which is needed to create an external domain ingress route to connect into your application.  Issue #74 was addressed for the application resource and it looks like it's available for the `qovery_container` resource but not for the `qovery_helm` resource.  This would be very useful/needed to completely setup external routing to a helm  installed app in qovery with TF.

**Comment by acarranoqovery** [comment]
Hi @whitedr , we have added the custom domain resource in the latest release (0.36.1)
