### ISSUE TITLE
environments destroy depend on cluster (parameter cluster required)

### ISSUE THREAD

**Issue by deromemont** [Qovery/terraform-provider-qovery#51]
If you try to delete all ressources in your account
Error: "You need first to delete all your environments before being able to delete your cluster"

Pass the parameter cluster_id in required
This way env depends on the cluster and the destroy will be OK

[cluster_id = qovery_cluster.my_cluster.id](https://github.com/Qovery/terraform-provider-qovery/blob/a6dbe96007080e3b08e2e5672d74179faccbb96d/examples/resources/qovery_environment/resource.tf#L7)

**Comment by benamib** [comment]
Hello @deromemont, thank you for your feedback 
i will make sure to update this on the next version
