### ISSUE TITLE
Qovery provider cannot access the account of the git account

### ISSUE THREAD

**Issue by json-lbtn** [Qovery/terraform-provider-qovery#54]
Hi there :panda_face: 

Since we switched on v0.4.1, we started to encounter a new issue about accessing the git account when creating new applications resources.

```
│ Error: Error on application create
│ 
│   with qovery_application.exa_app_crossbar,
│   on exa_services.tf line 356, in resource "qovery_application" "exa_app_crossbar":
│  356: resource "qovery_application" "exa_app_crossbar" {
│ 
│ Could not create application 'crossbar', unexpected error: 424 Failed
│ Dependency - Cannot access the account of the provided git account:
│ https://github.com/exa-finance/exa-app.git cannot get last commit id for
│ branch reverse-proxy
```

TOPO
- The `reverse-proxy` git branch exists :heavy_check_mark: 
- `qovery auth` for auth token refresh :heavy_check_mark: 
- `qovery token`  for api token refresh, stored on terraform cloud :heavy_check_mark: 

Any suggestions ? :leaves:

**Comment by evoxmusic** [comment]
@benamib is there anything missing from your perspective?

I guess that the EXA Qovery organization's owner account does not have the permissions to access the `https://github.com/exa-finance/exa-app.git` repository. What do you think?

**Comment by benamib** [comment]
Hello @json-lbtn, 
I think @evoxmusic is right, this look like a permissions issue. 
To make sure of this could you tell me if you are able to create a new application with this repository when using the console ?

**Comment by json-lbtn** [comment]
Hello @benamib 🍃 
Yes, I am actually able to create a new application using the console and the same `https://github.com/exa-finance/exa-app.git` repository.

**Comment by json-lbtn** [comment]
Hello @benamib @evoxmusic 🍃
I finally found out the origin of the problem.
Wrong branch name, it had a dirty `devops/` prefix. Didn't see it.

Thank you, gentlemen.
