### ISSUE TITLE
Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by json-lbtn** [Qovery/terraform-provider-qovery#69]
Hello there 🍃 

We are deploying our full stack in STOPPED state using the provider and it's producing an unexpected behaviour for the very last deploying application. 

> │ Error: Provider produced inconsistent result after apply
> │ 
> │ When applying changes to qovery_application.exa_app_finance_web_app,
> │ provider "provider[\"registry.terraform.io/qovery/qovery\"]" produced an
> │ unexpected new value: .state: was cty.StringVal("STOPPED"), but now
> │ cty.StringVal("RUNNING").
> │ 
> │ This is a bug in the provider, which should be reported in the provider's
> │ own issue tracker.
> Operation failed: failed running terraform apply (exit 1)

The stack is deployed this way : 
![image](https://user-images.githubusercontent.com/99829196/173310513-152c629d-8cae-4797-bd0f-e69e234d54bb.png)

We checked the terraform plan logs and we have this last application 'finance-web-app' deployed with the correct settings : 
>       + state                          = "STOPPED"

Do you have something in mind about this ?

**Comment by mzottolaqovery** [comment]
Hello @json-lbtn,
This issue has been fixed in release (0.14.2)[https://github.com/Qovery/terraform-provider-qovery/releases/tag/v0.14.2]
Thanks for having reporting the issue
