### ISSUE TITLE
Bug in Terraform provide in switching auto-preview on

### ISSUE THREAD

**Issue by dugwa** [Qovery/terraform-provider-qovery#73]
I have a child module that looks like this 

```
resource "qovery_application" "docker_application" {
  environment_id = qovery_environment.my_environment.id
  name           = var.app_name
  git_repository = {
    url       = var.git_url
    branch    = var.branch    # Optional
    root_path = var.root_path # Optional
  }

  build_mode            = var.docker_build_mode
  dockerfile_path       = var.dockerfile_path
  state                 = var.state
  auto_preview          = var.auto_preview
  cpu                   = var.cpu
  memory                = var.memory
  min_running_instances = var.min_running_instances
  max_running_instances = var.max_running_instances
  ports = [
    {
      internal_port       = var.application_internal_port
      external_port       = var.application_external_port
      protocol            = var.application_protocol
      publicly_accessible = var.application_publicly_accessible
    }
  ]
  secrets = var.application_secrets
}
```

`variable "auto_preview" {
  default = false
  type = bool
}
`

My root module (which calls the child module) looks like this

```
module "qovery_app" {

  source = "./modules/qovery/app-docker"

  app_name = "sample-app"

  git_url = "https://github.com/ABC/qovery-sample-app.git"

  branch = "develop"

  min_running_instances = 1

  max_running_instances = 1

  qovery_environment_mode = "DEVELOPMENT"

  qovery_environment_name = "infra-dev"

  qovery_token = var.qovery_token

  application_internal_port = 5555

  auto_preview = true

  application_secrets = [
    {
      key   = "DUMMY_SECRET_KEY"
      value = "DUMMY_SECRET_VALUE"
    },
    {
      key   = "DUMMY_SECRET_KEY2"
      value = "DUMMY_SECRET_VALUE2"
    }
  ]
}
```

when i execute terraform, i get the following errors 

`│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to
│ module.qovery_app.qovery_application.docker_application, provider
│ "module.qovery_app.provider[\"registry.terraform.io/qovery/qovery\"]"
│ produced an unexpected new value: .auto_preview: was cty.True, but now
│ cty.False.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
Operation failed: failed running terraform apply (exit 1)
`

The problem is that there is bug in the terraform provider to switch auto preview ON while creating an environment or even modifying an environment.

**Comment by dugwa** [comment]
This is also a blocker for us @evoxmusic 


we have to deploy every application twice 

- first time, switch off auto_preview 
second time, switch on auto_preview

**Comment by evoxmusic** [comment]
Ok I see with my team ASAP

**Comment by benamib** [comment]
Hi @dugwa 

Actually you don't have to change anything, it was an issue on the api side which was fixed and released. 
The field auto_preview was never used in case of app creation but only when updating the app.

It should work fine now 👍
