### ISSUE TITLE
Add "domain" attribute to terraform resource "qovery_application"

### ISSUE THREAD

**Issue by dugwa** [Qovery/terraform-provider-qovery#74]
https://registry.terraform.io/providers/Qovery/qovery/latest/docs/resources/application

This terraform resource is missing "domain" attribute - which is needed to create an external domain ingress route to connect into your application. 

This is causing problems for us becuase when we configure the domain on the UI and run terraform afterwards; terraform predictably removes the domain configuration

**Comment by evoxmusic** [comment]
Thank you @dugwa for the issue. @benamib will take a look

**Comment by dugwa** [comment]
@evoxmusic  - Thanks 

Please is there any update on this ?

**Comment by evoxmusic** [comment]
I can add it for tomorrow :)

**Comment by dugwa** [comment]
Thanks @evoxmusic

**Comment by evoxmusic** [comment]
I am working on it today. I keep you posted @dugwa

**Comment by dugwa** [comment]
thanks @benamib - i am assuming this feature will be in the plugin version 0.4.2 right ?

Is this now reflected in the  terraform documentation ?

https://registry.terraform.io/providers/Qovery/qovery/latest/docs/resources/application

**Comment by benamib** [comment]
Hi @dugwa 

This will be available in the next version 0.5.0, which will be release as soon as the tests are green 
They will be in the documentation after the release
