### ISSUE TITLE
Include terraform output in terraform resources

### ISSUE THREAD

**Issue by dugwa** [Qovery/terraform-provider-qovery#75]
This is a useful feature to have. 

- I want to be able to export the output values of my resources and persist it in my statefile. If these values are in the statefile, then it can be read using the terraform data function from another terraform process.
- Also terraform outputs are useful for debugging and diagnostic purposes

**Comment by evoxmusic** [comment]
@benamib , let me know if I can help for this request - it's a useful one

**Comment by benamib** [comment]
Hello @dugwa 

I'm not really familiar with the output feature, however I tried to use it using this [documentation](https://www.terraform.io/cli/commands/output) and I managed to make it work. 
Here's what I have done: 

`main.tf`
```
resource "qovery_project" "my_project" {
  organization_id = var.organization_id
  name = "MyProject"
}

output "project_name" {
  value = qovery_project.my_project.name
}
```
 
 I then used the `terraform refresh` command and got this output:
 ```
qovery_project.my_project: Refreshing state... [id=0f520166-8e82-48ee-af46-6e1a4ba562a3]

Outputs:

project_name = "MyProject"
 ```
 
 Finally when using the `terraform output` command I got this:
 ```
 project_name = "MyProject"
 ```
 
Let me know if this is what you were looking for or did I miss something ?

**Comment by dugwa** [comment]
thanks @benamib 

This actually works

**Comment by dugwa** [comment]
@benamib - please can this be reflected in the terraform documentation; on how to use the terraform outputs ?

thanks
