### ISSUE TITLE
Cannot override environment variable

### ISSUE THREAD

**Issue by json-lbtn** [Qovery/terraform-provider-qovery#86]
Hi there 🍃 

We just encountered an issue about overriding environment variables.
This is something we can do on the web console interface but there's an issue through the terraform provider : 
```
qovery_application.exa_app_ms_syncer: Creation complete after 1s [id=6d9eb82b-5190-4317-8bcc-a48e17e4b896]
╷
│ Error: Error on application environment variable create
│ 
│   with qovery_application.exa_app_finance_web_app,
│   on exa_services.tf line 1135, in resource "qovery_application" "exa_app_finance_web_app":
│ 1135: resource "qovery_application" "exa_app_finance_web_app" {
│ 
│ Could not create application environment variable
│ 'EXA_APP_WEBSOCKET_PROTOCOL', unexpected error: 409 Conflict - Variable
│ already exists: EXA_APP_WEBSOCKET_PROTOCOL
╵
Operation failed: failed running terraform apply (exit 1)
```

We want to override this EXA_APP_WEBSOCKET_PROTOCOL variable because it will be 'ws' for internal services and 'wss' for external services. 
We used to do it like that with the console. 

Do you think there is a simple way to quickly fix it on the provider or do we have to work with multiple services dedicated variables ?

**Comment by benamib** [comment]
Hi @json-lbtn 

This isn't an issue but a lack of implementation of the variable override feature on the provider side. 
It wasn't planned for now but I can add this to the roadmap, I can't tell you for sure when it will be available though.

As of today the only way to do this would be via the console (or the API).

**Comment by mzottolaqovery** [comment]
Hello @json-lbtn,
The overrides & aliases are now available in the provider
